In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make('FrozenLake-v1', render_mode='ansi')




/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [5]:
print(q_table)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
num_episodes =20000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [7]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
      # Exploration-exploitation trade-off
       exploration_rate_threshold = random.uniform(0, 1)
       if exploration_rate_threshold > exploration_rate:
           action = np.argmax(q_table[state,:])
       else:
           action = env.action_space.sample()
       new_state, reward, done, info = env.step(action)

       q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
       learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

       state = new_state
       rewards_current_episode += reward

       if done == True:
          break

    exploration_rate = min_exploration_rate + \
       (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)


rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000



/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


********Average reward per thousand episodes********

1000 :  0.047000000000000035
2000 :  0.23800000000000018
3000 :  0.3810000000000003
4000 :  0.5710000000000004
5000 :  0.6240000000000004
6000 :  0.6600000000000005
7000 :  0.6800000000000005
8000 :  0.6840000000000005
9000 :  0.6810000000000005
10000 :  0.6900000000000005
11000 :  0.6960000000000005
12000 :  0.7070000000000005
13000 :  0.6630000000000005
14000 :  0.6650000000000005
15000 :  0.6660000000000005
16000 :  0.6930000000000005
17000 :  0.7080000000000005
18000 :  0.6670000000000005
19000 :  0.6820000000000005
20000 :  0.6460000000000005


In [8]:
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.52738334 0.51859197 0.52173833 0.51624347]
 [0.35102858 0.34153351 0.4017781  0.49740475]
 [0.40242537 0.40643366 0.40244606 0.47132057]
 [0.36485891 0.2636244  0.38561602 0.46046355]
 [0.55291212 0.32429486 0.41790722 0.49003051]
 [0.         0.         0.         0.        ]
 [0.29807612 0.15529296 0.20417328 0.03941967]
 [0.         0.         0.         0.        ]
 [0.23540185 0.35738918 0.29501593 0.58980125]
 [0.427769   0.63148195 0.57293341 0.33329355]
 [0.54220096 0.35201452 0.39134496 0.32966428]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.41769765 0.66960772 0.71633608 0.43678833]
 [0.72171884 0.83915976 0.7363291  0.72416035]
 [0.         0.         0.         0.        ]]


In [14]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
       clear_output(wait=True)
       print(env.render())
       time.sleep(0.3)

       action = np.argmax(q_table[state,:])
       new_state, reward, done, info = env.step(action)

       if done:
          clear_output(wait=True)
          env.render()
          if reward == 1:
             print("****You reached the goal!****")
             time.sleep(3)
          else:
             print("****You fell through a hole!****")
             time.sleep(3)
          clear_output(wait=True)
          break
       state = new_state
env.close()


****You reached the goal!****
