In [ ]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [ ]:
env = gym.make('FrozenLake-v1', render_mode='ansi')




In [ ]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [ ]:
print(q_table)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
num_episodes =20000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [ ]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
      # Exploration-exploitation trade-off
       exploration_rate_threshold = random.uniform(0, 1)
       if exploration_rate_threshold > exploration_rate:
           action = np.argmax(q_table[state,:])
       else:
           action = env.action_space.sample()
       new_state, reward, done, info = env.step(action)

       q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
       learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

       state = new_state
       rewards_current_episode += reward

       if done == True:
          break

    exploration_rate = min_exploration_rate + \
       (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)


rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000



********Average reward per thousand episodes********

1000 :  0.05200000000000004
2000 :  0.18900000000000014
3000 :  0.3110000000000002
4000 :  0.4990000000000004
5000 :  0.6020000000000004
6000 :  0.6290000000000004
7000 :  0.5960000000000004
8000 :  0.6650000000000005
9000 :  0.6300000000000004
10000 :  0.6650000000000005
11000 :  0.6690000000000005
12000 :  0.5910000000000004
13000 :  0.6420000000000005
14000 :  0.6790000000000005
15000 :  0.6360000000000005
16000 :  0.6540000000000005
17000 :  0.5990000000000004
18000 :  0.6550000000000005
19000 :  0.6480000000000005
20000 :  0.6480000000000005


In [ ]:
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[5.90856924 5.82908924 5.81510412 5.80428414]
 [5.22155699 5.31117222 5.21052154 5.67160353]
 [5.54844744 5.41829605 5.44138375 5.47680343]
 [5.14140356 5.16934454 5.14079874 5.383726  ]
 [6.04798671 5.62288304 5.841983   5.61651572]
 [4.73836784 4.73690807 4.74049832 4.73870782]
 [5.23442894 5.12569467 5.72519309 4.96343249]
 [4.85831396 4.83747334 4.86766532 4.8479907 ]
 [5.47105971 5.89439142 5.68245233 6.47747742]
 [6.56677135 7.02069003 6.31611232 6.43932763]
 [6.60063388 6.28757849 6.0959194  5.89521733]
 [5.33423646 5.3383881  5.34443459 5.27938484]
 [4.9184267  4.9157617  4.91558727 4.84551787]
 [6.69510214 6.82066175 8.27967369 6.88285032]
 [7.9431093  9.33178468 8.00609479 8.0167621 ]
 [5.28413591 9.24506617 5.30615579 4.99766741]]
